name: Deploy
on:
  push:
  
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout  
      uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    #- name: Running test cases
    #  uses: convictional/trigger-workflow-and-wait@v1.3.0
    #  with:
    #    owner: cmnawagamuwa
    #    repo: AutomationWithGitHubAction
    #    github_token: ${{ secrets.PAT_TOKEN }}
    #    workflow_file_name: main.yml
        
  
    #- name: Test
    #  run: |
     #   curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
     #     -H "Accept: application/vnd.github.everest-preview+json" \
     #     -H "Content-Type: application/json" \
      #    'https://api.github.com/repos/cmnawagamuwa/AutomationWithGitHubAction/dispatches' \
      #    --data '{"event_type": "build_application"}'
          
    - name: Test from here
      uses: cmnawagamuwa/AutomationWithGitHubAction/dispatches@master
      with:
        owner: cmnawagamuwa
        repo: AutomationWithGitHubAction
        github_token: ${{ secrets.PAT_TOKEN }}
