name: .NET Core

on:
  pull_request:
  workflow_dispatch:
        

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout  
      uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    #- name: Trigger Workflow and Wait
  #uses: convictional/trigger-workflow-and-wait@v1.6.5

    - uses: convictional/trigger-workflow-and-wait@v1.6.5
      with:
        owner: cmnawagamuwa
        repo: AutomationWithGitHubAction
        github_token: ${{ secrets.PAT_TOKEN }}
        workflow_file_name: main.yml
    #- name: Test
    #  run: |
    #    curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
    #   -H "Accept: application/vnd.github.everest-preview+json" \
    #    -H "Content-Type: application/json" \
    #    'https://api.github.com/repos/cmnawagamuwa/AutomationWithGitHubAction/dispatches' \
    #    --data '{"event_type": "build_application"}'
