name: .NET Core

on:
  push: 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout  
      uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x   
        
    - name: Run Tests
      uses: cmnawagamuwa/AutomationWithGitHubAction/main.yml@v1
      
    #- name: Triggering the Regression Tests
     # run: |
     #   curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
     #   -H "Accept: application/vnd.github.everest-preview+json" \
     #   -H "Content-Type: application/json" \
     #   'https://api.github.com/repos/cmnawagamuwa/AutomationWithGitHubAction/dispatches' \
     #   --data '{"event_type": "build_application"}'
      
