name: main

on:
  push:   
  
jobs:  
  build: 
    
    runs-on: ubuntu-latest
    steps:
    - name: Checkout  
      uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x   
        
    - uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: cmnawagamuwa
        repo: myrepo
        github_token: ${{ secrets.PAT_TOKEN }}
        github_user: cmnawagamuwa
        workflow_file_name: main.yml
        ref: master
        wait_interval: 10
        client_payload: '{}'
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true
        
        
      
    #- name: Triggering the Regression Tests
     # run: |
     #   curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
     #   -H "Accept: application/vnd.github.everest-preview+json" \
     #   -H "Content-Type: application/json" \
     #   'https://api.github.com/repos/cmnawagamuwa/AutomationWithGitHubAction/dispatches' \
     #   --data '{"event_type": "build_application"}'
      
