name: main

on:
  pull_request:
    
     
  #push:

jobs:  
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: mdecoleman/pr-branch-name@1.2.0
      id: vars
      with:
        repo-token: ${{ secrets.PAT_TOKEN }}
    - run: echo ${{ steps.vars.outputs.branch }}
    
    - name: Checkout  
      uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x   
       
    - name: Executing Regression Tests 
      uses: convictional/trigger-workflow-and-wait@v1.6.5
      with:
        owner: aaditya-20
        repo: TestWati
        github_token: ${{ secrets.PAT_TOKEN }}
        github_user: aaditya-20
        workflow_file_name: main.yml
        ref: master
        wait_interval: 10
        client_payload: '{"branch_name":"${{ steps.vars.outputs.branch }}"}'
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true
        comment_downstream_url: ${{ github.event.pull_request.comments_url }}
    
    - name: Get Test Report Link from Test Repo
      id: get_report_link
      run: |
        REPORT_URL=$(curl -s "https://api.github.com/repos/aaditya-20/TestWati/actions/runs?event=workflow_run_completed&status=completed" \
          -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
          | jq -r '.workflow_runs[0].artifacts_url')
        echo "::set-output name=report_url::$REPORT_URL"
          
    - name: Comment on PR with Test Report Link
      uses: thollander/actions-comment-pull-request@v2
      with:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        message: |
           Hello world ! :wave:
        comment_tag: execution
